# Prometheus Configuration for Aura AI Platform Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nginx API Gateway
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics
    scrape_interval: 30s

  # Visual Analysis Service
  - job_name: 'visual-analysis'
    static_configs:
      - targets: ['visual_analysis_service:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Outfit Recommendation Service
  - job_name: 'outfit-recommendation'
    static_configs:
      - targets: ['outfit_recommendation_service:8001']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Conversational AI Service
  - job_name: 'conversational-ai'
    static_configs:
      - targets: ['conversational_ai_service:8003']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # GPU Metrics (if available)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9445']
    scrape_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules
rule_files:
  - "alert_rules.yml"
