# Outfit Recommendation Service - Kubernetes Deployment and Service
# OutfitTransformer-based style recommendations and compatibility scoring

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outfit-recommendation-deployment
  namespace: aura-ai
  labels:
    app.kubernetes.io/name: outfit-recommendation
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: aura-ai-platform
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: outfit-recommendation
  template:
    metadata:
      labels:
        app: outfit-recommendation
        app.kubernetes.io/name: outfit-recommendation
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: aura-ai-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
      # Model downloader for OutfitTransformer models
      - name: model-downloader
        image: gcr.io/PROJECT_ID/aura-model-downloader:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          echo "Downloading OutfitTransformer models..."
          if [ ! -f /models/outfit-transformer/pytorch_model.bin ]; then
            echo "Downloading OutfitTransformer model..."
            python -c "
            import torch
            from transformers import AutoModel
            model = AutoModel.from_pretrained('outfit-transformer-v1')
            model.save_pretrained('/models/outfit-transformer')
            torch.save(model.state_dict(), '/models/outfit-transformer/pytorch_model.bin')
            "
          fi
          if [ ! -f /models/style-embeddings/embeddings.pkl ]; then
            echo "Downloading pre-computed style embeddings..."
            python -c "
            import pickle
            import requests
            # Download pre-computed style embeddings
            response = requests.get('https://storage.googleapis.com/aura-models/style-embeddings.pkl')
            with open('/models/style-embeddings/embeddings.pkl', 'wb') as f:
                f.write(response.content)
            "
          fi
          echo "OutfitTransformer model download completed"
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: aura-ai-secrets
              key: HF_TOKEN
        - name: TRANSFORMERS_CACHE
          value: "/models"
        volumeMounts:
        - name: model-storage
          mountPath: /models
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi

      containers:
      - name: outfit-recommendation
        image: gcr.io/PROJECT_ID/aura-outfit-recommendation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        
        env:
        - name: SERVICE_NAME
          value: "outfit-recommendation"
        - name: MODEL_PATH
          value: "/app/models"
        - name: DEVICE
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: DEVICE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: LOG_LEVEL
        - name: MAX_WORKERS
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: MAX_WORKERS
        - name: CACHE_SIZE
          value: "1000"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: aura-ai-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aura-ai-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: REDIS_HOST
        - name: VISUAL_ANALYSIS_URL
          valueFrom:
            configMapKeyRef:
              name: aura-ai-config
              key: VISUAL_ANALYSIS_URL
        
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          readOnly: true
        - name: logs-storage
          mountPath: /app/logs
        
        resources:
          requests:
            cpu: 1500m
            memory: 6Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 3000m
            memory: 12Gi
            nvidia.com/gpu: 1
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 15"

      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: logs-pvc

      imagePullSecrets:
      - name: aura-ai-registry-secret

      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4

      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - outfit-recommendation
              topologyKey: kubernetes.io/hostname

---
# Outfit Recommendation Service
apiVersion: v1
kind: Service
metadata:
  name: outfit-recommendation-service
  namespace: aura-ai
  labels:
    app.kubernetes.io/name: outfit-recommendation
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: outfit-recommendation
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP

---
# Horizontal Pod Autoscaler for Outfit Recommendation
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: outfit-recommendation-hpa
  namespace: aura-ai
  labels:
    app.kubernetes.io/name: outfit-recommendation
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: outfit-recommendation-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: nvidia.com/gpu
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
